export const allFields: any[] = [
    {field: "ClientID", select: true}, 
    {field: "Salutation", select: true}, 
    {field: "FirstName", select: true}, 
    {field: "LastName", select: true}, 
    {field: "Email", select: true}, 
    {field: "ContactNo", select: true}, 
    {field: "DateJoin", select: true}, 
    {field: "Fax"}, 
    {field: "NRIC"}, 
    {field: "CompanyName"}, 
    {field: "Website"}, 
    {field: "StreetName"}, 
    {field: "Block"}, 
    {field: "UnitNo"}, 
    {field: "PostalCode"}, 
    {field: "Country"}, 
    {field: "Attn"}, 
    {field: "PaymentTermID"}, 
    {field: "PaymentDetail"}, 
    {field: "AddedByID"}, 
    {field: "AddedBy"}, 
    {field: "AddedDate"}, 
    {field: "AddedByType"}, 
    {field: "ModifiedByID"}, 
    {field: "ModifiedBy"}, 
    {field: "ModifiedDate"}, 
    {field: "ModifiedByType"}, 
    {field: "Status"}, 
    {field: "StatusDate"}, 
    {field: "Remarks"}, 
    {field: "Keyword"}
];

export const customerTiles: any[] = [
    {label: 'ClientID', cols: 1, rows: 1, color: 'E3F2FD'},
    {label: 'Salutation', cols: 1, rows: 1, color: 'E3F2FD'},
    {label: 'FirstName', cols: 2, rows: 1, color: 'E3F2FD'},
    {label: 'LastName', cols: 2, rows: 1, color: 'E3F2FD'},
    {label: 'Email', cols: 4, rows: 1, color: 'E3F2FD'},
    {label: 'ContactNo', cols: 1, rows: 1, color: 'E3F2FD'},
    {label: 'Fax', cols: 1, rows: 1, color: 'E3F2FD'},

    {label: 'NRIC', cols: 1, rows: 1, color: 'E3F2FD'},
    {label: 'CompanyName', cols: 5, rows: 1, color: 'E3F2FD'},
    {label: 'Website', cols: 4, rows: 1, color: 'E3F2FD'},
    {label: 'DateJoin', cols: 2, rows: 1, color: 'E3F2FD'},

    {label: 'StreetName', cols: 4, rows: 1, color: 'E3F2FD'},
    {label: 'Block', cols: 1, rows: 1, color: 'E3F2FD'},
    {label: 'UnitNo', cols: 1, rows: 1, color: 'E3F2FD'},
    {label: 'PostalCode', cols: 1, rows: 1, color: 'E3F2FD'},
    {label: 'Country', cols: 1, rows: 1, color: 'E3F2FD'},
    {label: 'Attn', cols: 4, rows: 1, color: 'E3F2FD'},

    {label: 'PaymentTermID', cols: 1, rows: 1, color: 'E3F2FD'},
    {label: 'PaymentDetail', cols: 11, rows: 1, color: 'E3F2FD'},

    {label: 'AddedByID', cols: 1, rows: 1, color: 'E3F2FD'},
    {label: 'AddedBy', cols: 3, rows: 1, color: 'E3F2FD'},
    {label: 'AddedDate', cols: 2, rows: 1, color: 'E3F2FD'},
    {label: 'AddedByType', cols: 6, rows: 1, color: 'E3F2FD'},

    {label: 'ModifiedByID', cols: 1, rows: 1, color: 'E3F2FD'},
    {label: 'ModifiedBy', cols: 3, rows: 1, color: 'E3F2FD'},
    {label: 'ModifiedDate', cols: 2, rows: 1, color: 'E3F2FD'},
    {label: 'ModifiedByType', cols: 6, rows: 1, color: 'E3F2FD'},

    {label: 'Status', cols: 2, rows: 1, color: 'E3F2FD'},
    {label: 'StatusDate', cols: 2, rows: 1, color: 'E3F2FD'},
    {label: 'Remarks', cols: 8, rows: 1, color: 'E3F2FD'},

    {label: 'Keyword', cols: 12, rows: 1, color: 'E3F2FD'},
];